export const TRIP_PAGE_COPY = {
  loading: "Loading your trip details...",
  galleryLabel: "Gallery",
  statusLabel: "Status",
  locationLabel: "Location",
  dateLabel: "Starting Date",
  typeLabel: "Trip Type",
  itineraryTitle: "Itinerary",
  policyTitle: "Terms and Conditions",
  hotelTitle: "Hotel Information",
  hostedBy: "Hosted by",
  bookingTitle: "Booking Details",
  pricePerPerson: "Price per person",
  reviewsTitle: "Reviews",
  reviewsFallback: "No reviews yet. Be the first to leave a review.",
  bookNow: "Book Now",
  showPolicy: "Show Policy",
  showItinerary: "Show Itinerary",
  guideEmail: "Email",
  guidePhone: "Phone",
  noPolicy: "Policy details were not provided for this trip.",
  noFacilities: "Facilities were not listed in the repo data.",
};

export const PAYMENT_PAGE_COPY = {
  eyebrow: "Secure Checkout",
  heading: "Complete your booking with confidence.",
  summaryTitle: "Booking Summary",
  paymentTitle: "Payment Details",
  travelerTitle: "Travellers",
  noTravelers: "No travellers added yet.",
  totalCost: "Total Cost",
  discountedCost: "Final Cost (after 10% discount)",
  nameOnCard: "Name on Card",
  country: "Country",
  cardInfo: "Enter your card information",
  termsPrefix: "I agree to the",
  processing: "Processing...",
  proceed: "Proceed to Payment",
  poweredBy: "Powered by",
  successTitle: "Booking Confirmed!",
  successBody: "Thank you for your payment. Your trip is confirmed!",
};

export const BOOKING_MODAL_COPY = {
  reviewTitle: "Review Your Package",
  instructionTitle: "Important Instruction",
  instructionBody: "Please enter details for each traveler. All fields are mandatory.",
  addTraveler: "Add Traveller",
  proceed: "Proceed to Payment",
  priceSummary: "Price Summary",
  basePrice: "Base Price (per person)",
  totalTravelers: "Total Travelers",
  totalBeforeDiscount: "Total Price (before discount)",
  discount: "Discount (10%)",
  gst: "GST (10%)",
  totalPayable: "Total Payable",
  travelerDetails: "Enter Traveller Details",
  saveTraveler: "Save Traveller",
  name: "Name",
  governmentId: "Government ID",
  age: "Age",
  terms: "Terms and Conditions",
};
